"""new mood column added

Revision ID: e4bf96b3c9ab
Revises: 
Create Date: 2018-03-12 11:06:56.417786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bf96b3c9ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('mood', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'mood')
    # ### end Alembic commands ###
